
test_suite(
    name = "AllTests",
    tests = [
        "//submodules/AyuGramCore:AyuGramFilterEngineTests",
        "//submodules/TgVoipWebrtc:TgCallsTests",
    ],
    visibility = [
        "//visibility:public",
    ],
)
