import Foundation

public func ayuGramIsChineseLanguage(_ languageCode: String) -> Bool {
    let normalized = languageCode.lowercased()
    return normalized == "zh" || normalized.hasPrefix("zh-") || normalized.hasPrefix("zh_")
}

public func ayuGramLocalized(_ english: String, languageCode: String) -> String {
    guard ayuGramIsChineseLanguage(languageCode) else {
        return english
    }

    return ayuGramChineseStrings[english] ?? english
}

private let ayuGramChineseStrings: [String: String] = [
    "AyuGram": "AyuGram",
    "GHOST MODE": "幽灵模式",
    "Use Global Ghost Mode": "使用全局幽灵模式",
    "Send Read Messages": "发送已读回执",
    "MESSAGE HISTORY": "消息历史",
    "Save Deleted Messages": "保存已删除消息",
    "Save Message Edit History": "保存消息编辑历史",
    "MESSAGE SHOT": "消息截图",
    "Show Message Shot": "显示消息截图",
    "Background": "背景",
    "Date": "日期",
    "Reactions": "回应",
    "Header Decorations": "顶部装饰",
    "Colorful Replies": "彩色回复",
    "Reveal Spoilers": "显示剧透内容",
    "Embedded Theme": "嵌入主题",
    "FILTERS": "过滤器",
    "Enable Filters": "启用过滤器",
    "Apply Filters in Chats": "在聊天中应用过滤器",
    "Filters": "过滤器",
    "APPEARANCE": "外观",
    "Semi-Transparent Deleted Messages": "半透明显示已删除消息",
    "Message Bubble Radius": "消息气泡圆角",
    "Avatar Corners": "头像圆角",
    "Single Bubble Corner Radius": "统一气泡圆角",
    "Remove Message Tail": "移除消息尾巴",
    "Bottom Info Icons": "底部信息图标",
    "CHAT CONTROLS": "聊天控制",
    "Hide Fast Share": "隐藏快速分享",
    "Show Peer ID": "显示 Peer ID",
    "Show Message Seconds": "显示消息秒数",
    "Hide Similar Channels": "隐藏相似频道",
    "Disable Open Link Warning": "关闭打开链接警告",
    "Disable Ads": "禁用广告",
    "Disable Stories": "禁用 Stories",
    "Hide Premium Statuses": "隐藏 Premium 标识",
    "Hide Notification Counters": "隐藏通知计数",
    "Hide Notification Badge": "隐藏应用角标",
    "Hide All Chats Folder": "隐藏全部聊天文件夹",
    "COMPOSER": "输入栏",
    "Attach Button": "附件按钮",
    "Commands Button": "命令按钮",
    "Emoji Button": "表情按钮",
    "Microphone Button": "麦克风按钮",
    "Auto-Delete Button": "自动删除按钮",
    "Gift Button": "礼物按钮",
    "AI Editor Button": "AI 编辑按钮",
    "Attach Popup": "附件弹窗",
    "Emoji Popup": "表情弹窗",
    "DRAWER": "侧栏 / 底栏",
    "My Profile": "我的资料",
    "Bots": "机器人",
    "New Group": "新建群组",
    "New Channel": "新建频道",
    "Contacts": "联系人",
    "Calls": "通话",
    "Saved Messages": "收藏夹",
    "Local Read Toggle": "本地已读开关",
    "Server Read Toggle": "服务器已读开关",
    "Night Mode Toggle": "夜间模式开关",
    "Ghost Toggle": "幽灵模式开关",
    "Streamer Toggle": "直播隐私开关",
    "Ghost Tray Toggle": "托盘幽灵模式开关",
    "Streamer Tray Toggle": "托盘直播隐私开关",
    "TRANSLATION": "翻译",
    "Translation Provider": "翻译服务",
    "WEB VIEW": "网页视图",
    "Spoof as Android": "伪装为 Android",
    "Increase WebView Height": "增加 WebView 高度",
    "Increase WebView Width": "增加 WebView 宽度",
    "ADVANCED": "高级",
    "Streamer Mode": "直播隐私模式",
    "Crash Reporting": "崩溃报告",
    "Hidden": "隐藏",
    "Native": "系统原生",
    "current": "当前",
    "Search": "搜索",
    "Deleted Messages": "已删除消息",
    "Edit History": "编辑历史",
    "Clear": "清除",
    "No deleted messages saved for this chat.": "此聊天尚未保存已删除消息。",
    "No deleted messages match this search.": "没有匹配搜索的已删除消息。",
    "Clear saved deleted-message history for this chat?": "要清除此聊天保存的已删除消息历史吗？",
    "No edited history saved for this message.": "此消息尚未保存编辑历史。",
    "View Edit History": "查看编辑历史",
    "Message Details": "消息详情",
    "Message Shot": "消息截图",
    "User Messages": "此用户的消息",
    "Repeat Message": "重复发送消息",
    "Read Until": "读到此处",
    "Hide Message Locally": "仅本地隐藏消息",
    "Add Filter": "添加过滤器",
    "Remove Shadow Ban": "移除影子封禁",
    "Shadow Ban": "影子封禁",
    "Select text before adding a filter.": "请先选中文本再添加过滤器。",
    "Shadow ban will be available after filter storage is implemented.": "影子封禁会在过滤器存储完成后可用。",
    "Hide this message only for this local account?": "仅在当前本地账号隐藏这条消息？",
    "Hide": "隐藏",
    "Unknown": "未知",
    "No text": "无文本",
    "Author": "作者",
    "Message ID": "消息 ID",
    "Edit Date": "编辑日期",
    "Captured": "捕获时间",
    "Stable ID": "稳定 ID",
    "Thread ID": "话题 ID",
    "Media": "媒体",
    "Peer ID": "Peer ID",
    "Author ID": "作者 ID",
    "Views": "查看数",
    "Forwards": "转发数",
    "Entity Count": "实体数量",
    "Global Unique ID": "全局唯一 ID",
    "Grouping Key": "分组 Key",
    "Forward Source Message ID": "转发来源消息 ID",
    "Forward Source Peer ID": "转发来源 Peer ID",
    "Forward Date": "转发日期",
    "Copy Peer ID": "复制 Peer ID",
    "Copy Message ID": "复制消息 ID",
    "Copy Author ID": "复制作者 ID",
    "Copy Thread ID": "复制话题 ID",
    "Copy Message Text": "复制消息文本",
    "Copy All Details": "复制全部详情",
    "None": "无",
    "Image": "图片",
    "Sticker": "贴纸",
    "Instant Video": "圆形视频",
    "Video": "视频",
    "Music": "音乐",
    "Voice": "语音",
    "File": "文件",
    "Webpage": "网页",
    "Contact": "联系人",
    "Map": "位置",
    "Poll": "投票",
    "Dice": "骰子",
    "Game": "游戏",
    "Invoice": "账单",
    "Story": "Story",
    "Giveaway": "抽奖",
    "Giveaway Results": "抽奖结果",
    "Paid Content": "付费内容",
    "Todo": "待办",
    "Expired Content": "过期内容",
    "Action": "操作"
]
